gen : gen.c
	gcc -O2 gen.c -o gen -Dk=3

decode : decode.h decode.c
	gcc -O2 -o decode.o -c decode.c
encode : encode.h encode.c
	gcc -O2 -o encode.o -c encode.c
fileio : fileio.h fileio.c
	gcc -O2 -o fileio.o -c fileio.c
