#!/bin/bash
VARS=""
RET="return"
for i in {1..60}; do VARS="$VARS\nlong v$i;"; done
for i in {1..59}; do RET="$RET v$i ^"; done
RET="$RET v60;"
cat <(echo -e "long f(long a1, long a2, long a3) {") <(echo -e "$VARS") <(cat) <(echo "$RET") <(echo "}") | gcc -x c - -S -o - | grep -v "^\s*\." | grep -v ':$'
